import { useCallback } from 'react';

import { toast } from 'sonner';

import { useNavigationState } from '../useNavigationState';
import { cleanText } from '../../utils/text';
import { downloadDataUrlFile, shareImageDataUrl } from '../../utils/share';
import { formatTime12h } from '../../utils/time';

export function useAppViewDepartment({ access, data, management, operations, sales, ui }: any) {
  const handleLogoutFromUi = useCallback(() => {
    access.handleLogout();
    toast.info('Sesión cerrada');
  }, [access.handleLogout]);

  const {
    canAccessDashboard,
    canAccessStats,
    canAccessCierres,
    canAccessResults,
    canAccessUsers,
    canAccessArchive,
    canAccessAdminConfig,
    canAccessLiquidation,
    visibleNavigationItems,
    salesAccessError,
    canSell,
  } = useNavigationState({
    activeTab: access.activeTab,
    setActiveTab: access.setActiveTab,
    currentUserRole: access.currentUserRole,
    userProfile: access.userProfile,
    operationalSellerId: access.operationalSellerId,
  });

  const modalsProps = {
    showSettingsModal: ui.showSettingsModal,
    setShowSettingsModal: ui.setShowSettingsModal,
    globalSettings: data.globalSettings,
    setGlobalSettings: data.setGlobalSettings,
    isPrimaryCeoUser: access.isPrimaryCeoUser,
    handleDeleteAllSalesData: operations.handleDeleteAllSalesData,
    showFastEntryModal: sales.showFastEntryModal,
    setShowFastEntryModal: sales.setShowFastEntryModal,
    setCart: sales.setCart,
    fastEntrySelectedLotteries: sales.fastEntrySelectedLotteries,
    chancePrice: sales.chancePrice,
    plAmount: sales.plAmount,
    showTicketModal: access.showTicketModal,
    setShowTicketModal: access.setShowTicketModal,
    results: data.results,
    lotteries: data.lotteries,
    users: data.users,
    confirmModal: ui.confirmModal,
    setConfirmModal: ui.setConfirmModal,
    multiDeleteModal: ui.multiDeleteModal,
    setMultiDeleteModal: ui.setMultiDeleteModal,
    reuseModal: ui.reuseModal,
    setReuseModal: ui.setReuseModal,
    activeLotteries: sales.activeLotteries,
    handleReuseSelect: sales.handleReuseSelect,
    showCheckoutModal: sales.showCheckoutModal,
    setShowCheckoutModal: sales.setShowCheckoutModal,
    customerName: sales.customerName,
    setCustomerName: sales.setCustomerName,
    confirmSale: sales.confirmSale,
    isSubmittingSale: sales.isSubmittingSale,
    showLotteryModal: access.showLotteryModal,
    setShowLotteryModal: access.setShowLotteryModal,
    editingLottery: access.editingLottery,
    setEditingLottery: access.setEditingLottery,
    saveLottery: management.saveLottery,
    showUserModal: ui.showUserModal,
    setShowUserModal: ui.setShowUserModal,
    editingUser: ui.editingUser,
    setEditingUser: ui.setEditingUser,
    saveUser: management.saveUser,
    currentUserRole: access.userProfile?.role,
    isSavingUser: management.isSavingUser,
    showInjectionModal: ui.showInjectionModal,
    setShowInjectionModal: ui.setShowInjectionModal,
    setIsInjectionOnly: ui.setIsInjectionOnly,
    setInjectionTargetUserEmail: ui.setInjectionTargetUserEmail,
    setInjectionDefaultType: ui.setInjectionDefaultType,
    setInjectionInitialAmount: ui.setInjectionInitialAmount,
    currentUser: access.user,
    userProfile: access.userProfile,
    injectionTargetUserEmail: ui.injectionTargetUserEmail,
    injectionDefaultType: ui.injectionDefaultType,
    injectionInitialAmount: ui.injectionInitialAmount,
    isInjectionOnly: ui.isInjectionOnly,
    setInjections: data.setInjections,
    refreshAuditLogs: data.refreshAuditLogs,
  };

  const sidebarProps = {
    isMobile: access.isMobile,
    isOnline: access.isOnline,
    isSidebarOpen: access.isSidebarOpen,
    setIsSidebarOpen: access.setIsSidebarOpen,
    activeTab: access.activeTab,
    setActiveTab: access.setActiveTab,
    visibleNavigationItems,
    handleLogoutFromUi,
  };

  const mainContentProps = {
    isSidebarOpen: access.isSidebarOpen,
    setIsSidebarOpen: access.setIsSidebarOpen,
    todayStats: operations.todayStats,
    handleLogoutFromUi,
    mainScrollRef: data.mainScrollRef,
    handleMainTouchStart: data.handleMainTouchStart,
    handleMainTouchMove: data.handleMainTouchMove,
    handleMainTouchEnd: data.handleMainTouchEnd,
    activeTab: access.activeTab,
    canAccessDashboard,
    canAccessStats,
    canAccessCierres,
    canAccessResults,
    canAccessAdminConfig,
    canAccessUsers,
    canAccessLiquidation,
    canAccessArchive,
    todayStr: operations.todayStr,
    userProfile: access.userProfile,
    injections: data.injections,
    results: data.results,
    users: data.users,
    userStats: operations.userStats,
    operationalSellerId: access.operationalSellerId,
    historyTickets: access.historyTickets,
    ticketMatchesGlobalChancePrice: data.ticketMatchesGlobalChancePrice,
    lotteries: data.lotteries,
    reportLotteries: data.resultLotteries,
    cleanText,
    formatTime12h,
    dailyAuditLogs: data.dailyAuditLogs,
    appAlerts: data.appAlerts,
    appAlertsLoading: data.appAlertsLoading,
    onUnpinAppAlert: data.handleUnpinAppAlert,
    isMultipleMode: sales.isMultipleMode,
    setIsMultipleMode: sales.setIsMultipleMode,
    showMultiSelect: sales.showMultiSelect,
    setShowMultiSelect: sales.setShowMultiSelect,
    multiLottery: sales.multiLottery,
    setMultiLottery: sales.setMultiLottery,
    activeLotteries: sales.activeLotteries,
    lotteriesLoading: data.lotteriesLoading,
    selectedLottery: data.selectedLottery,
    setSelectedLottery: data.setSelectedLottery,
    globalSettings: data.globalSettings,
    betType: sales.betType,
    setBetType: sales.setBetType,
    setNumber: sales.setNumber,
    setQuantity: sales.setQuantity,
    setPlAmount: sales.setPlAmount,
    setFocusedField: sales.setFocusedField,
    findActiveLotteryByName: sales.findActiveLotteryByName,
    focusedField: sales.focusedField,
    numberInputRef: sales.numberInputRef,
    amountInputRef: sales.amountInputRef,
    number: sales.number,
    quantity: sales.quantity,
    plAmount: sales.plAmount,
    amountEntryStarted: sales.amountEntryStarted,
    setAmountEntryStarted: sales.setAmountEntryStarted,
    handleKeyPress: sales.handleKeyPress,
    handleBackspace: sales.handleBackspace,
    handleClear: sales.handleClear,
    addToCart: sales.addToCart,
    canSell,
    salesAccessError,
    cart: sales.cart,
    clearCart: sales.clearCart,
    updateCartItemQuantity: sales.updateCartItemQuantity,
    updateCartItemAmount: sales.updateCartItemAmount,
    removeFromCart: sales.removeFromCart,
    chancePrice: sales.chancePrice,
    editingTicketId: access.editingTicketId,
    cancelEdit: sales.cancelEdit,
    cartTotal: sales.cartTotal,
    handleSell: sales.handleSell,
    setShowFastEntryModal: sales.setShowFastEntryModal,
    isSpecial4DSelected: sales.isSpecial4DSelected,
    special4DUnitPrice: sales.special4DUnitPrice,
    historyDate: access.historyDate,
    setHistoryDate: access.setHistoryDate,
    applyOperationalQuickDate: access.applyOperationalQuickDate,
    recentOperationalDates: operations.recentOperationalDates,
    historyFilter: access.historyFilter,
    setHistoryFilter: access.setHistoryFilter,
    selectedUserToLiquidate: access.selectedUserToLiquidate,
    setSelectedUserToLiquidate: access.setSelectedUserToLiquidate,
    selectedManageUserEmail: management.selectedManageUserEmail,
    setSelectedManageUserEmail: management.setSelectedManageUserEmail,
    showGlobalScope: access.showGlobalScope,
    setShowGlobalScope: access.setShowGlobalScope,
    canUseGlobalScope: access.canUseGlobalScope,
    historyLotteryCards: operations.historyLotteryCards,
    filteredTickets: operations.filteredTickets,
    getTicketPrizes: data.getTicketPrizes,
    setExpandedLotteries: access.setExpandedLotteries,
    expandedLotteries: access.expandedLotteries,
    setLotteryPages: access.setLotteryPages,
    isLotteryOpenForSales: sales.isLotteryOpenForSales,
    historyTypeFilterCode: operations.historyTypeFilterCode,
    sortedLotteries: data.sortedLotteries,
    setShowTicketModal: access.setShowTicketModal,
    cancelTicket: sales.cancelTicket,
    isTicketClosed: sales.isTicketClosed,
    isTicketHasResults: sales.isTicketHasResults,
    user: access.user,
    editTicket: sales.editTicket,
    reuseTicket: sales.reuseTicket,
    setShowUserModal: ui.setShowUserModal,
    setEditingUser: ui.setEditingUser,
    setShowInjectionModal: ui.setShowInjectionModal,
    setInjectionTargetUserEmail: ui.setInjectionTargetUserEmail,
    setInjectionDefaultType: ui.setInjectionDefaultType,
    setIsInjectionOnly: ui.setIsInjectionOnly,
    canManageResults: management.canManageResults,
    isCeoUser: management.isCeoUser,
    businessDayKey: access.businessDayKey,
    setEditingResult: management.setEditingResult,
    deleteResult: management.deleteResult,
    availableResultLotteries: management.availableResultLotteries,
    setActiveTab: access.setActiveTab,
    canAccessAllUsers: access.canAccessAllUsers,
    globalChancePriceFilter: data.globalChancePriceFilter,
    setGlobalChancePriceFilter: data.setGlobalChancePriceFilter,
    shareImageDataUrl,
    downloadDataUrlFile,
    editingResult: management.editingResult,
    cancelResultEdition: management.cancelResultEdition,
    setResultFormLotteryId: management.setResultFormLotteryId,
    resultFormLotteryId: management.resultFormLotteryId,
    lotteryById: management.lotteryById,
    resultFormFirstPrize: management.resultFormFirstPrize,
    setResultFormFirstPrize: management.setResultFormFirstPrize,
    resultFormSecondPrize: management.resultFormSecondPrize,
    setResultFormSecondPrize: management.setResultFormSecondPrize,
    resultFormThirdPrize: management.resultFormThirdPrize,
    setResultFormThirdPrize: management.setResultFormThirdPrize,
    handleCreateResultFromForm: management.handleCreateResultFromForm,
    visibleResults: management.visibleResults,
    resultStatusMap: management.resultStatusMap,
    getResultKey: data.getResultKey,
    setShowSettingsModal: ui.setShowSettingsModal,
    setEditingLottery: access.setEditingLottery,
    setShowLotteryModal: access.setShowLotteryModal,
    toggleLotteryActive: management.toggleLotteryActive,
    deleteLottery: management.deleteLottery,
    setGlobalSettings: data.setGlobalSettings,
    handleDeleteAllSalesData: operations.handleDeleteAllSalesData,
    deleteUser: management.deleteUser,
    canMutateInjection: management.canMutateInjection,
    updateInjectionAmount: management.updateInjectionAmount,
    deleteInjection: management.deleteInjection,
    sendUserMessage: data.sendUserMessage,
    isPrimaryCeoUser: access.isPrimaryCeoUser,
    setConsolidatedMode: operations.setConsolidatedMode,
    consolidatedMode: operations.consolidatedMode,
    consolidatedReportDate: operations.consolidatedReportDate,
    setConsolidatedReportDate: operations.setConsolidatedReportDate,
    setConsolidatedStartDate: operations.setConsolidatedStartDate,
    setConsolidatedEndDate: operations.setConsolidatedEndDate,
    consolidatedStartDate: operations.consolidatedStartDate,
    consolidatedEndDate: operations.consolidatedEndDate,
    generateConsolidatedReport: operations.generateConsolidatedReport,
    isGeneratingYesterdayReport: operations.isGeneratingYesterdayReport,
    liquidationDate: access.liquidationDate,
    setLiquidationDate: access.setLiquidationDate,
    liquidacionQuickDateOptions: operations.liquidacionQuickDateOptions,
    isLiquidationDataLoading: access.isLiquidationDataLoading,
    liquidationUsers: operations.liquidationUsers,
    selectedLiquidationSettlement: operations.selectedLiquidationSettlement,
    liquidationGlobalSummary: operations.liquidationGlobalSummary,
    liquidationUserSummaries: operations.liquidationUserSummaries,
    liquidationRangeStartDate: operations.liquidationRangeStartDate,
    setLiquidationRangeStartDate: operations.setLiquidationRangeStartDate,
    liquidationRangeEndDate: operations.liquidationRangeEndDate,
    setLiquidationRangeEndDate: operations.setLiquidationRangeEndDate,
    liquidationRangeReport: operations.liquidationRangeReport,
    isLiquidationRangeLoading: operations.isLiquidationRangeLoading,
    fetchLiquidationRangeReport: operations.fetchLiquidationRangeReport,
    amountPaid: operations.amountPaid,
    setAmountPaid: operations.setAmountPaid,
    amountDirection: operations.amountDirection,
    setAmountDirection: operations.setAmountDirection,
    handleLiquidate: operations.handleLiquidate,
    handleLiquidateRange: operations.handleLiquidateRange,
    liquidationPreview: operations.liquidationPreview,
    archiveDate: access.archiveDate,
    setArchiveDate: access.setArchiveDate,
    archiveUserEmail: access.archiveUserEmail,
    setArchiveUserEmail: access.setArchiveUserEmail,
    fetchArchiveData: operations.fetchArchiveData,
    isArchiveLoading: access.isArchiveLoading,
    archiveTickets: access.archiveTickets,
    archiveInjections: access.archiveInjections,
    auditLogsLoading: data.auditLogsLoading,
    refreshAuditLogs: data.refreshAuditLogs,
    buildFinancialSummary: data.buildFinancialSummary,
    fetchArchiveSalesReport: operations.fetchArchiveSalesReport,
    searchArchiveTickets: operations.searchArchiveTickets,
    fetchArchiveLiquidations: operations.fetchArchiveLiquidations,
    handleUpdateChancePrice: management.handleUpdateChancePrice,
    personalChancePrice: management.personalChancePrice,
    setPersonalChancePrice: management.setPersonalChancePrice,
    canUpdatePersonalChancePrice: ui.canUpdatePersonalChancePrice,
    isUpdatingChancePrice: management.isUpdatingChancePrice,
    isUpdatingSpecial4dPreference: management.isUpdatingSpecial4dPreference,
    requestSpecial4dPreferenceChange: management.requestSpecial4dPreferenceChange,
    handleUpdatePassword: management.handleUpdatePassword,
    newPassword: management.newPassword,
    setNewPassword: management.setNewPassword,
    confirmPassword: management.confirmPassword,
    setConfirmPassword: management.setConfirmPassword,
    isUpdatingPassword: management.isUpdatingPassword,
  };

  return {
    handleLogoutFromUi,
    mainContentProps,
    modalsProps,
    sidebarProps,
  };
}
